const express = require('express')

const authRoutes = require('../modules/auth/routes')
const itemRoutes = require('../modules/items/routes')
const interestRoutes = require('../modules/interests/routes')
const chatRoutes = require('../modules/chat/routes')
const barterRoutes = require('../modules/barter/routes')
const walletRoutes = require('../modules/wallet/routes')
const qrRoutes = require('../modules/qr/routes')
const wasteRoutes = require('../modules/waste/wasteRoutes')
const notificationRoutes = require('../modules/notifications/notificationsRoutes')
const ecoRoutes = require('../modules/eco/routes')
const collectorRoutes = require('../modules/collectors/routes')
const mediaRoutes = require('../modules/media/routes')
const historyRoutes = require('../modules/history/routes')
const campaignRoutes = require('../modules/campaigns/routes')
const adminRoutes = require('../modules/admin/routes')
const reportRoutes = require('../modules/reports/routes')
const oceanReportRoutes = require('../modules/oceanReports/routes')
const aiRoutes = require('./aiRoutes')
const transactionRoutes = require('../modules/transactions/routes')

const routes = express.Router()

routes.get('/', (req, res) => res.json({ service: 'EcoBarter+ API', version: '1.0.0' }))

routes.use('/auth', authRoutes)
routes.use('/items', itemRoutes)
routes.use('/interests', interestRoutes)
routes.use('/chat', chatRoutes)
routes.use('/barter', barterRoutes)
routes.use('/wallet', walletRoutes)
routes.use('/qr', qrRoutes)
routes.use('/waste', wasteRoutes)
routes.use('/notifications', notificationRoutes)
routes.use('/eco', ecoRoutes)
routes.use('/collectors', collectorRoutes)
routes.use('/media', mediaRoutes)
routes.use('/history', historyRoutes)
routes.use('/campaigns', campaignRoutes)
routes.use('/admin', adminRoutes)
routes.use('/reports', reportRoutes)
routes.use('/ocean-reports', oceanReportRoutes)
routes.use('/ai', aiRoutes)
routes.use('/transactions', transactionRoutes)

module.exports = { routes }

